//A continuación escribimos nuestras reglas en un archivo REGISTRO_PROGDIARIA.drl


package rules
import classes.Registro;

//---Cambio de Prog Diaria-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Mantener frecuencia"
    salience 2
	dialect "java"
    when
       registroObject: Registro(getEvaluacion()=="Excelente")
       Registro((getTiempo() <= (getNivel().getMaxTime()*10) && getIndice()==0) || 
       (getEvaluacion()=="Excelente" && (getTiempo() > (getNivel().getMaxTime()*10))) ||  //falta probar
       (getEvaluacion()=="Buena" && (getTiempo() <= (getNivel().getMaxTime()*10)))) //falta probar
    then 
       registroObject.setAccion("PERMANECE");
end	
rule "Disminuir frecuencia"
    salience 1
	dialect "java"
    when
       registroObject: Registro(getEvaluacion()=="Excelente")
       Registro(getTiempo() <= (getNivel().getMaxTime()*10))
       Registro(getIndice()>0)
    then 
       registroObject.setIndice(registroObject.getIndice()-1);
       registroObject.setAccion("DISMINUYE");
end

/*
rule "Disminuir frecuencia"
    salience 0
	dialect "java"
    when
       registroObject: Registro(getEvaluacion()=="Excelente")
       Registro(getTiempo() <= (getNivel().getMaxTime()*10))
       Registro(getNivel().getFrecuencias().indexOf(getFrec())>0)
    then 
       registroObject.setAccion("DISMINUYE");
    	//System.out.println("DISMINUYE");
end
rule "Mantener frecuencia"
    salience 0
	dialect "java"
    when
       (registroObject: Registro(getEvaluacion() =="Excelente")
       Registro(getTime()<=getNivel().getMaxTime())
       Registro(getNivel().getFrecuencias().indecOf()==0)) || 
       (registroObject: Registro(getEvaluacion() =="Excelente")
       Registro(getTime()>getNivel().getMaxTime())) || 
       (registroObject: Registro(getEvaluacion() =="Buena")
       Registro(getTime()<=getNivel().getMaxTime()))
    then 
    	 registroObject.setAccion("PERMANECE");
    	 //System.out.println("PERMANECE");
 end	 
 rule "Aumentar frecuencia"
    salience 0
	dialect "java"
    when
       (registroObject: Registro(getEvaluacion() =="Buena")
       Registro(getTime()>getNivel().getMaxTime())
       Registro(getNivel().getFrecuencias().indecOf()==0)) || 
       (registroObject: Registro(getEvaluacion() =="Excelente")
       Registro(getTime()>getNivel().getMaxTime())) || 
       (registroObject: Registro(getEvaluacion() =="Buena")
       Registro(getTime()<=getNivel().getMaxTime()))
    then 
    	 registroObject.setAccion("AUMENTAR");
    	 //System.out.println("AUMENTAR");
end
*/

