//A continuación escribimos nuestras reglas en un archivo proyeccionNivel.drl


package rules

import classes.Nivel;
import classes.Alumno;
import classes.ProyeccionNivel;
import classes.ProyeccionAnual;

//---Nivel3A-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Frecuencia 3A 1.0a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getAnteSuc() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 3A 1.5a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getAnteSuc() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.5);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 3A 2.0a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getAnteSuc() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(2);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 3A 1.7a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getAnteSuc() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.7);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 3A 1.2a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getAnteSuc() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.2);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 3A 2.2a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getAnteSuc() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(2.2);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 3A 1.5a2"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <= 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getAnteSuc() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.5);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 3A 1.6a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <= 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getAnteSuc() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 3A 2.2a2"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <= 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getAnteSuc() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(2.2);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 3A 2.0b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <= 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getAnteSuc() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(2);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
rule "Frecuencia 3A 1.5a3"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <= 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getAnteSuc() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.5);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
rule "Frecuencia 3A 2.2b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() <= 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getAnteSuc() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(2.2);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
rule "Frecuencia 3A 1.4a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() > 5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.4);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
rule "Frecuencia 3A 1.0a2"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() > 5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
rule "Frecuencia 3A 1.5b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() > 5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.5);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
rule "Frecuencia 3A 1.2a2"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() > 5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.2);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
rule "Frecuencia 3A 1.7a2"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() > 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.7);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
rule "Frecuencia 3A 1.1a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() > 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
rule "Frecuencia 3A 1.8a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() > 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.8);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
rule "Frecuencia 3A 1.4b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "3A")
       ProyeccionNivel(getAlumno().getGradoNum() > 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.4);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );    
end
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//---Nivel2A-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Frecuencia 2A 1.0a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 1.6a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 1.6a2"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 2.0b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(2);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 1.6b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 2.0b2"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(2);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 1.6a3"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 2.0b3"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(2);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 1.0a2"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() >5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 1.6a4"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() >5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 1.0a3"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() >5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 2.0b4"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() >5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(2);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 1.2a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() >5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.2);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 1.6b2"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() >5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 1.6a5"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() >5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia 2A 2.0b5"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "2A")
       ProyeccionNivel(getAlumno().getGradoNum() >5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
       ProyeccionNivel(getAlumno().getCuenta() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(2);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------

//---NivelA-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Frecuencia A 1"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "A")
       ProyeccionNivel(getAlumno().getGradoNum() <=6)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia A 1.4"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "A")
       ProyeccionNivel(getAlumno().getGradoNum() <=6)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
    then 
   		proyeccionNivelObject.setFrecuenciaEstudio(1.4);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );

end
rule "Frecuencia A 1.5a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "A")
       ProyeccionNivel(getAlumno().getGradoNum() <=6)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.5);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia A 1.6a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "A")
       ProyeccionNivel(getAlumno().getGradoNum() <=6)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia A 1.6b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "A")
       ProyeccionNivel(getAlumno().getGradoNum() <=6)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getTrabajoB() == 1)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia A 1.9a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "A")
       ProyeccionNivel(getAlumno().getGradoNum() <=6)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getTrabajoB() == 0)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.9);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia A 1b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "A")
       ProyeccionNivel(getAlumno().getGradoNum() >6)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 1)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia A 1.5b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "A")
       ProyeccionNivel(getAlumno().getGradoNum() >6)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 0)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.5);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia A 1.6c"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "A")
       ProyeccionNivel(getAlumno().getGradoNum() > 6)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getTrabajoB() == 1)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("c");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia A 1.8a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "A")
       ProyeccionNivel(getAlumno().getGradoNum() > 6)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getTrabajoB() == 0)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.8);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
//----------------------------------------------------------------------------------------------------------------------
//---NivelB-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Frecuencia B 1.0a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "B")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia B 1.3a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "B")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 1)
       ProyeccionNivel(getAlumno().getConcentracion() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.3);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia B 1.7a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "B")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 0)
       ProyeccionNivel(getAlumno().getConcentracion() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.7);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia B 1.4a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "B")
       ProyeccionNivel(getAlumno().getGradoNum() <=5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getTrabajoB() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.4);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia B 1.0a2"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "B")
       ProyeccionNivel(getAlumno().getGradoNum() >5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia B 1.4b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "B")
       ProyeccionNivel(getAlumno().getGradoNum() > 5)
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getTrabajoB() == 0)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.4);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia B 1.5a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "B")
       ProyeccionNivel(getAlumno().getGradoNum() > 5)
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getTrabajoB() == 1)
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(1.5);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
        
end
rule "Frecuencia nivelIncorrectoB1"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "B")
       ProyeccionNivel((getAlumno().getGradoNum() <= 5 && getAlumno().getFluidez() == 0 && getAlumno().getTrabajoB() == 0) ||
       (getAlumno().getGradoNum() <= 5 && getAlumno().getFluidez() == 1 && getAlumno().getTrabajoB() == 0 && getAlumno().getConcentracion() == 0) ||
       				   (getAlumno().getGradoNum() > 5 && getAlumno().getFluidez() == 0 && getAlumno().getTrabajoB() == 0))
    then 
        proyeccionNivelObject.setFrecuenciaEstudio(0);
    	proyeccionNivelObject.setFrecuenciaInciso(" ");
        System.out.println("El alumno no cumple con las habilidades necesarias. Revisar nivel de ubicación.");
end


//-----------------------------------------------------------------------------------------------------------------------------------------------------------------

//---NivelC-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Frecuencia C 1.0a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "C")
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getCalculoMental() == 1)
       ProyeccionNivel(getAlumno().getProcedimientosCortos() == 1)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia C 1.2a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "C")
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getCalculoMental() == 1)
       ProyeccionNivel(getAlumno().getProcedimientosCortos() == 0)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.2);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia C 1.4a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "C")
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getCalculoMental() == 0)
       ProyeccionNivel(getAlumno().getProcedimientosCortos() == 1)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.4);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia C 1.5a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "C")
       ProyeccionNivel(getAlumno().getFluidez() == 1)
       ProyeccionNivel(getAlumno().getCalculoMental() == 0)
       ProyeccionNivel(getAlumno().getProcedimientosCortos() == 0)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.5);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia C 1.7a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "C")
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getCalculoMental() == 1)
       ProyeccionNivel(getAlumno().getProcedimientosCortos() == 1)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.7);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia C 1.6a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "C")
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getCalculoMental() == 1)
       ProyeccionNivel(getAlumno().getProcedimientosCortos() == 0)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.6);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() + " procediemintos cortos: " + proyeccionNivelObject.getAlumno().getProcedimientosCortos());
end
rule "Frecuencia nivelIncorrectoC"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "C")
       ProyeccionNivel(getAlumno().getFluidez() == 0)
       ProyeccionNivel(getAlumno().getCalculoMental() == 0)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(0);
    	proyeccionNivelObject.setFrecuenciaInciso("");
        System.out.println("El alumno no cumple con las habilidades necesarias. Revisar nivel de ubicación.");
end
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------
//---NivelD-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Frecuencia D 1.1a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "D")
       ProyeccionNivel(getAlumno().getDivisionConResta() == 1)
       ProyeccionNivel(getAlumno().getSimplificacion() == 1)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.1);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia D 1.5a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "D")
       ProyeccionNivel(getAlumno().getDivisionConResta() == 1)
       ProyeccionNivel(getAlumno().getSimplificacion() == 0)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.5);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia D 1.3b"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "D")
       ProyeccionNivel(getAlumno().getDivisionConResta() == 0)
       ProyeccionNivel(getAlumno().getSimplificacion() == 1)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.3);
    	proyeccionNivelObject.setFrecuenciaInciso("b");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
rule "Frecuencia D 1.4a"
	salience 0
	dialect "java"
    when
       proyeccionNivelObject: ProyeccionNivel(getAlumno().getNivelActual() == "D")
       ProyeccionNivel(getAlumno().getDivisionConResta() == 0)
       ProyeccionNivel(getAlumno().getSimplificacion() == 0)
    then 
    	proyeccionNivelObject.setFrecuenciaEstudio(1.4);
    	proyeccionNivelObject.setFrecuenciaInciso("a");
        System.out.println("La frecuencia del nivel: " + proyeccionNivelObject.getAlumno().getNivelActual() + " es: " + proyeccionNivelObject.getFrecuenciaEstudio() + " " + proyeccionNivelObject.getFrecuenciaInciso() );
end
//-----------------------------------------------------------------------------------------------------------------------------------------------------------------

rule "desempeño Bajo nivel"
dialect "java"
	salience 8
	    when
        nivelObject : Nivel((getDesempeñoNivel() == "malo" && getDesempeñoGeneral() == "malo") ||
        					(getDesempeñoNivel() == "malo" && getDesempeñoGeneral() == "medio") ||
        					(getDesempeñoNivel() == "medio" && getDesempeñoGeneral() == "malo"))
    then 
        nivelObject.setNivelMessage("Bajo, + " + nivelObject.getDesempeñoBajo());
        nivelObject.setDesempeño(nivelObject.getDesempeñoBajo());
end
rule "desempeño Medio nivel"
	salience 8
    when
    	nivelObject : Nivel((getDesempeñoNivel() == "malo" && getDesempeñoGeneral() == "bueno") ||
        					(getDesempeñoNivel() == "medio" && getDesempeñoGeneral() == "medio") ||
        					(getDesempeñoNivel() == "bueno" && getDesempeñoGeneral() == "malo"))
    then 
        nivelObject.setNivelMessage("Medio, + " + nivelObject.getDesempeñoMedio());
        nivelObject.setDesempeño(nivelObject.getDesempeñoMedio());
end
rule "desempeño Alto nivel"
	salience 8
    when
    	nivelObject : Nivel((getDesempeñoNivel() == "medio" && getDesempeñoGeneral() == "bueno") ||
        					(getDesempeñoNivel() == "bueno" && getDesempeñoGeneral() == "bueno") ||
        					(getDesempeñoNivel() == "bueno" && getDesempeñoGeneral() == "medio"))
    then 
        nivelObject.setNivelMessage("Alto, + " + nivelObject.getDesempeñoAlto());
        nivelObject.setDesempeño(nivelObject.getDesempeñoAlto());
end
//-----------------------------------------------------------------------------------------------------------------

rule "desempeño Bajo general"
dialect "java"
	salience 10
	    when
        alumnoObject : Alumno(getPuntajeDesempeño() <= 30)
    then 
    	alumnoObject.setDesempeño(alumnoObject.getDesempeñoBajo());
    	System.out.println("El desempeño general es "+ alumnoObject.getDesempeño());
        
end
rule "desempeño Medio general"
	salience 10
    when
        alumnoObject : Alumno(getPuntajeDesempeño() > 30 && getPuntajeDesempeño() <= 75)
    then 
        alumnoObject.setDesempeño(alumnoObject.getDesempeñoMedio());
        System.out.println("El desempeño general es "+ alumnoObject.getDesempeño());
end
rule "desempeño Alto general"
	salience 10
    when
        alumnoObject : Alumno(getPuntajeDesempeño() > 75 && getPuntajeDesempeño() <= 95)
    then 
       alumnoObject.setDesempeño(alumnoObject.getDesempeñoAlto());
       System.out.println("El desempeño general es "+ alumnoObject.getDesempeño());
end