//A continuación escribimos nuestras reglas en un archivo REGISTRO_PROGDIARIA.drl


package rules
import classes.Registro;

//---Prog Diaria-----------------------------------------------------------------------------------------------------------------------------------------------
//---CLASIFICACIÓN DE LA EVALUACIÓN-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Evaluacion excelente"
	salience 0
	dialect "java"
    when
       registroObject: Registro(getNumNoventa()<=4)
       Registro(getNumCien()>=6)
    then 
       registroObject.setEvaluacion("Excelente");
end
rule "Evaluacion buena"
    salience 0
	dialect "java"
    when
       registroObject: Registro(getNumTriangulo() + getNumFlecha()<=4)
       Registro(getNumCien()>=4)
       //Registro(getNumOchenta() + getNumNoventa() + getNumSetenta == 10 - getNumTriangulo() + getNumFlecha() + getNumCien())
    then 
    	registroObject.setEvaluacion("Buena");
end
rule "Evaluacion mala"
    salience 0
	dialect "java"
    when
       registroObject: Registro((getNumTriangulo() + getNumFlecha())>4)
    then 
    	registroObject.setEvaluacion("Mala");
end
//---Cambio de Prog Diaria-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Disminuir frecuencia"
    salience 0
	dialect "java"
    when
       registroObject: Registro(getEvaluacion=="Excelente")
       Registro(getTime()<=getNivel().getMaxTime())
       Registro(getNivel().getFrecuencias().indecOf()>0)
    then 
    	System.out.rintln("DISMINUYE");
    	
rule "Mantener frecuencia"
    salience 0
	dialect "java"
    when
       (registroObject: Registro(getEvaluacion=="Excelente")
       Registro(getTime()<=getNivel().getMaxTime())
       Registro(getNivel().getFrecuencias().indecOf()==0)) || 
       (registroObject: Registro(getEvaluacion=="Excelente")
       Registro(getTime()>getNivel().getMaxTime())) || 
       (registroObject: Registro(getEvaluacion=="Buena")
       Registro(getTime()<=getNivel().getMaxTime()))
    then 
    	 System.out.rintln("PERMANECE");
    	 
 rule "Aumentar frecuencia"
    salience 0
	dialect "java"
    when
       (registroObject: Registro(getEvaluacion=="Buena")
       Registro(getTime()>getNivel().getMaxTime())
       Registro(getNivel().getFrecuencias().indecOf()==0)) || 
       (registroObject: Registro(getEvaluacion=="Excelente")
       Registro(getTime()>getNivel().getMaxTime())) || 
       (registroObject: Registro(getEvaluacion=="Buena")
       Registro(getTime()<=getNivel().getMaxTime()))
    then 
    	 System.out.rintln("AUMENTAR");
end