//A continuación escribimos nuestras reglas en un archivo REGISTRO_PROGDIARIA.drl


package rules
import classes.Registro;

//---Prog Diaria-----------------------------------------------------------------------------------------------------------------------------------------------
//---CLASIFICACIÓN DE LA EVALUACIÓN-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Evaluacion excelente"
	salience 0
	dialect "java"
    when
       registroObject: Registro(getNumNoventa()<=4)
       Registro(getNumCien()>=6)
       Registro(getNumTriangulo()==0)
       Registro(getNumOchenta()==0)
       Registro(getNumSetenta()==0)
       Registro(getNumFlecha()==0)
    then 
       registroObject.setEvaluacion("Excelente");
end
rule "Evaluacion buena"
    salience 1
	dialect "java"
    when
       registroObject: Registro((getNumTriangulo() + getNumFlecha())<=4)
       Registro(getNumCien()>=4)
       //Registro((getNumOchenta() + getNumNoventa() + getNumSetenta())>=2)
    then 
    	registroObject.setEvaluacion("Buena");
end
rule "Evaluacion mala"
    salience 2
	dialect "java"
    when
       registroObject: Registro(getEvaluacion() == null)
    then 
    	registroObject.setEvaluacion("Mala");
end

//---Cambio de Prog Diaria-----------------------------------------------------------------------------------------------------------------------------------------------
rule "Disminuir frecuencia"
    salience 0
	dialect "java"
    when
       registroObject: Registro(getEvaluacion() =="Excelente")
       Registro(getTiempo()<=getNivel().getMaxTime())
       Registro(getNivel().getFrecuencias().indexOf(getFrec())>0)
    then 
    	registroObject.setAccion("DISMINUYE");
    	//System.out.println("DISMINUYE");
end /*	
rule "Mantener frecuencia"
    salience 0
	dialect "java"
    when
       (registroObject: Registro(getEvaluacion() =="Excelente")
       Registro(getTime()<=getNivel().getMaxTime())
       Registro(getNivel().getFrecuencias().indecOf()==0)) || 
       (registroObject: Registro(getEvaluacion() =="Excelente")
       Registro(getTime()>getNivel().getMaxTime())) || 
       (registroObject: Registro(getEvaluacion() =="Buena")
       Registro(getTime()<=getNivel().getMaxTime()))
    then 
    	 registroObject.setAccion("PERMANECE");
    	 //System.out.println("PERMANECE");
 end	 
 rule "Aumentar frecuencia"
    salience 0
	dialect "java"
    when
       (registroObject: Registro(getEvaluacion() =="Buena")
       Registro(getTime()>getNivel().getMaxTime())
       Registro(getNivel().getFrecuencias().indecOf()==0)) || 
       (registroObject: Registro(getEvaluacion() =="Excelente")
       Registro(getTime()>getNivel().getMaxTime())) || 
       (registroObject: Registro(getEvaluacion() =="Buena")
       Registro(getTime()<=getNivel().getMaxTime()))
    then 
    	 registroObject.setAccion("AUMENTAR");
    	 //System.out.println("AUMENTAR");
end
*/

